name: Sync Content to Backup Blog

on:
  push:
    branches:
      - v4

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      # Шаг 1: Клонирование основного репозитория
      - name: Checkout Main Repository
        uses: actions/checkout@v4
        with:
          ref: v4  # Указываем ветку v4
          path: main

      # Шаг 2: Клонирование резервного репозитория
      - name: Checkout Backup Repository
        uses: actions/checkout@v4
        with:
          repository: Gennady87/blog
          ref: v4  # Указываем ветку v4
          token: ${{ secrets.BACKUP_TOKEN }}
          path: backup

      # Шаг 3: Синхронизация каталога content
      - name: Sync Content Directory
        run: |
          rsync -av --delete main/content/ backup/content/

      # Шаг 4: Коммит и пуш изменений в резервный репозиторий
      - name: Commit and Push Changes
        run: |
          cd backup
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add content/
          git commit -m "Sync content from Quartz_blog (branch v4)" || echo "No changes to commit"
          git push origin v4
